.TH EMPTY 1 "January 2025" "1.0" "User Commands"
.SH NAME
empty \- A command to empty a directory or file.
.SH SYNOPSIS
.B empty
[\fBfile\fR|\fBdirectory\fR]
.SH DESCRIPTION
The \fBempty\fR command can be used to clear the contents of a directory or a file.

If the argument is a directory, all its contents (including subdirectories and hidden files) are removed.

If the argument is a file, its contents are emptied.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays the help message for the command.

.SH EXAMPLES
.TP
.B empty /path/to/directory
Empties all files and subdirectories in the specified directory.

.TP
.B empty /path/to/file
Clears the contents of the specified file.

.SH AUTHOR
Written by M.Vasanthadithya.

.SH REPORTING BUGS
Report bugs to <vasanth.mundrathi@gmail.com>.

.SH SOCIAL MEDIAS
INSTA:<vasnthadithya_m>
GITHUB:<Vasanthfeb13>

.SH COPYRIGHT
Copyright © 2025. This is free software; you are free to change and redistribute it.



